### ISSUE TITLE
Rename `DoBoCas_overpass.txt` to `DoBoCas.overpassql`

### ISSUE THREAD

**Issue by FloEdelmann** [ie3-institute/OSMoGrid#243]
`*.overpassql` is now the recommended file extension for Overpass QL: [OSM Wiki: Overpass QL § File extension](https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#File_extension)
*(**Disclaimer:** I added that section after [some discussion](https://wiki.openstreetmap.org/wiki/Talk:Overpass_API/Overpass_QL#Recommended_file_extension?).)*

I propose to rename all Overpass QL files in this repo to `*.overpassql` for consistency.

Context: GitHub's syntax highlighting engine requires that 200 repositories use the same file extension before they consider supporting that syntax and file extension: https://github.com/github/linguist/issues/5890

**Comment by sebastian-peter** [comment]
Sounds fine to me, I think a good file name would be `DoBoCas.overpassql`

**Comment by FloEdelmann** [comment]
Sure, I was only suggesting the new file extension. Renaming the file to avoid duplication of course makes sense :slightly_smiling_face:
