### ISSUE TITLE
Implement ResultEventListener 

### ISSUE THREAD

**Issue by johanneshiry** [ie3-institute/OSMoGrid#74]
Implement an actor that is able to process specific result events. This issue needs to consider a) that we use akka typed and therefore a corresponding hierarchy in a sealed trait for ResultEventListener needs to be designed and b) that there may be different result events (e.g. final results as GridInputModels or intermediate results) which correspondingly needs a sealed trait hierarchy of processable results. 
Furthermore, there is no need to implement specific writer for the GridInputModel, as we can use existing ones from the PowerSystemDataModel package. 

- [ ] design a result model hierarchy
- [ ] design a result actor 
- [ ] implement the result model hierarchy
- [ ] implement the result actor 
- [ ] write tests for both

**Comment by ckittl** [comment]
As of conceptual discussion we foresee to alter the interface a bit:

- We assume, that _all_ `ResultListener` are "fire and forget". Thus, spawn the needed actors as late as possible and let them die right after handling the event
- We expect to get a distinct feedback for the termination of the actor (either by death watch or distinct message)
- If _all_ `ResultListener` report successful termination, the whole run is considered to be finished
- Interface to the outside world: Handover a queue and spawn an equivalent listener actor within OSMoGrid to fill the queueu
