### ISSUE TITLE
Cleanup build.gradle

### ISSUE THREAD

**Issue by johanneshiry** [ie3-institute/OSMoGrid#76]
build.gradle currently contains several old dependencies. When the switch to scala 3 is complete (including all implementations) this file should be revised and cleaned.

**Comment by sebastian-peter** [comment]
As we're currently (and probably in the future) only use scalatest in this project, we could remove the dependency on `spock` (and therefore probably on `objenesis` and `cglib`). And there's more...

**Comment by sebastian-peter** [comment]
`OSMonaut` is also not used anymore
